#!/bin/bash
mysql -u root -p123pass << EOF
CREATE DATABASE $1;
CREATE USER "$1"@"localhost" IDENTIFIED BY "$1";
GRANT USAGE ON *.* TO "$1"@"localhost" IDENTIFIED BY "$1" WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0 ;
GRANT ALL PRIVILEGES ON newtbase.* TO "$1"@"localhost";
EOF
